### ISSUE TITLE
-Xbootclasspath/p is no longer a supported option

### ISSUE THREAD

**Issue by joker234** [chenkelmann/neo2-awt-hack#3]
Starting with PyCharm 2019.1, the `-Xbootclasspath/p` option is not working anymore. I suppose it's because the current pycharm version is delivered with Java 11. Is there another possiblity to use this hack, that worked wonderful for so many years?

```bash
$ pycharmpath/jre64/bin/java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-b159.30)
OpenJDK 64-Bit Server VM (build 11.0.2+9-b159.30, mixed mode)
```

```bash
$ pycharmpath/bin/pycharm.sh                          :(
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
-Xbootclasspath/p is no longer a supported option.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

```bash
$ < ~/.PyCharm2019.1/config/pycharm64.vmoptions
# custom PyCharm VM options

-Xms128m
-Xmx4096m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-Djdk.http.auth.tunneling.disabledSchemes=""
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Dawt.useSystemAAFontSettings=lcd
-Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine
-Xbootclasspath/p:/<path-to-hack>/neo2-awt-hack/neo2-awt-hack-0.4-java8oracle.jar
```

**Comment by joker234** [comment]
see also https://youtrack.jetbrains.com/issue/VIM-987#focus=streamItem-27-3367182.0-0 and https://wiki.neo-layout.org/ticket/364#comment:14

**Comment by chenkelmann** [comment]
I am afraid not, unless there is some alternative to `-Xbootclasspath` I do not know of. 
The basic principle of the hack is to replace java system classes with hacked custom versions to work around the issues IntelliJ and other AWT/Swing programs have with the extra modifier keys. Unless there is some other way of replacing java system classes on the fly there is no way to apply this hack any longer.

**Comment by joker234** [comment]
thx for the quick response. If anyone has the same issues with the IdeaVim Plugin, this PR is working for me on all tested systems (sadly not for the built-in terminal) https://github.com/JetBrains/ideavim/pull/155
