### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by 2er0** [chenkelmann/neo2-awt-hack#4]
IntelliJ, … switch to Java 11.
With Java 11 the `-Xbootclasspath/p:` hack is no longer permitted and `-Xbootclasspath/a` is unable to do the trick.

The new version of `-Xbootclasspath/p:` is `--path-module` but I was unable to get it running with the prebuild jar.
`--patch-module java.awt.KeyEvent=/home/four/tmp/neo2-awt-hack-0.4-java8oracle.jar`

Any ideas?

Some Links to the problem
[how-to-add-a-jar-to-the-boot-classpath-in-java-9](https://stackoverflow.com/questions/48148607/how-to-add-a-jar-to-the-boot-classpath-in-java-9)
[9-relnote-issues](https://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html)
[OpenJDK](http://openjdk.java.net/jeps/261)
[some-blog](https://blog.codefx.org/java/five-command-line-options-hack-java-module-system/)
[some-other-blog](https://dzone.com/articles/javafx-on-jdk-11)

**Comment by chenkelmann** [comment]
Sorry, I do not think that the current approach still works with Java 11. You could try replacing the classes directly in the open jdk installation, though.

**Comment by david0** [comment]
Replacing the files in rt.jar directly worked for me btw.

**Comment by 2er0** [comment]
Which rt.jar do you mean - there are too many on my system

**Comment by chenkelmann** [comment]
You have to find out which java version is used to start the application you want to apply the hack for. Normally the `rt.jar` you are looking for should be in a subfolder where the java executable resides. You can try renaming the `rt.jar` files you have to something like `rt.jar.bak`. If the application you want to use the hack for does not start anymore, you found the right one.

**Comment by david0** [comment]
Sorry, I tested on Java 8. Newer Java versions don't ship KeyEvent.class in rt.jar anymore because of the modularization. I did not yet find out were it went.
