### ISSUE TITLE
Found a ticket which fixes it for JetBrains products

### ISSUE THREAD

**Issue by JThyroff** [chenkelmann/neo2-awt-hack#7]
Maybe this is also helpful for you.

I just had to tick "Use national layouts for shortcuts (requires restart)" in the keymap settings. (Ubuntu 20.04, PyCharm, IntelliJ Ultimate)

https://youtrack.jetbrains.com/issue/IDEA-197762
https://www.jetbrains.com/help/idea/settings-keymap.html#other

**Comment by chenkelmann** [comment]
Thanks a lot! I tested it and it works great on my setup (Linux Mint 19.3 Cinnamon, IntelliJ IDEA 2021.1 (Ultimate Edition) Build #IU-211.6693.111).
I will update the README to reflect this - I cannot see a reason to use the hack anymore, this is definitely the cleaner solution.
